# Application Configurations
spring.application.name=bfhl

# Server Port (Dynamic port binding for platforms like Railway/Render)
server.port=${PORT:8080}

# Logging Configurations
logging.level.com.uzair.bfhl=DEBUG
logging.level.org.springframework.web=INFO

# Springdoc / OpenAPI Configurations
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
